# np.sort

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([47, 89, 27, 53, 97, 86, 98, 97, 58, 90,  4, 55, 16, 51, 25])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[30, 44, 60,  1],
       [66, 47, 26, 90],
       [61, 12, 68, 30],
       [46, 47, 41, 83],
       [80, 63, 19, 55],
       [32, 80, 38, 60]])

In [4]:
np.sort(a)

array([ 1,  6, 20, 22, 22, 29, 29, 31, 41, 53, 61, 67, 92, 97, 98])

In [7]:
np.sort(a)[::-1] #descending order

array([98, 97, 92, 67, 61, 53, 41, 31, 29, 29, 22, 22, 20,  6,  1])

In [6]:
np.sort(b,axis=0) #column wise

array([[ 9,  4, 24,  9],
       [11,  6, 40, 17],
       [20, 12, 54, 44],
       [33, 44, 54, 52],
       [39, 82, 80, 62],
       [76, 90, 96, 95]])

# np.append

In [8]:
a

array([22, 53, 92, 41, 97,  1, 29, 98,  6, 29, 61, 20, 22, 67, 31])

In [9]:
np.append(a,200)

array([ 22,  53,  92,  41,  97,   1,  29,  98,   6,  29,  61,  20,  22,
        67,  31, 200])

In [10]:
b

array([[ 9, 82, 54, 52],
       [76,  6, 80, 17],
       [11,  4, 54, 62],
       [33, 90, 96, 95],
       [20, 44, 24, 44],
       [39, 12, 40,  9]])

In [12]:
np.append(b,np.ones((b.shape[0],1)))

array([ 9., 82., 54., 52., 76.,  6., 80., 17., 11.,  4., 54., 62., 33.,
       90., 96., 95., 20., 44., 24., 44., 39., 12., 40.,  9.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [11]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[ 9., 82., 54., 52.,  1.],
       [76.,  6., 80., 17.,  1.],
       [11.,  4., 54., 62.,  1.],
       [33., 90., 96., 95.,  1.],
       [20., 44., 24., 44.,  1.],
       [39., 12., 40.,  9.,  1.]])

In [15]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[ 9.        , 82.        , 54.        , 52.        ,  0.27985941],
       [76.        ,  6.        , 80.        , 17.        ,  0.92982781],
       [11.        ,  4.        , 54.        , 62.        ,  0.49317637],
       [33.        , 90.        , 96.        , 95.        ,  0.41551531],
       [20.        , 44.        , 24.        , 44.        ,  0.83660812],
       [39.        , 12.        , 40.        ,  9.        ,  0.47359202]])

# np.concatenate

In [18]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print("\n",d)

[[0 1 2]
 [3 4 5]]

 [[ 6  7  8]
 [ 9 10 11]]


In [19]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [20]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# np.unique

In [22]:
e = np.array([1,2,3,3,4,4,5,5,6,6,7,7,8])
e

array([1, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8])

In [23]:
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7, 8])

# np.expand_dims

In [25]:
a

array([22, 53, 92, 41, 97,  1, 29, 98,  6, 29, 61, 20, 22, 67, 31])

In [27]:
a.shape

(15,)

In [26]:
# 1D to 2D
np.expand_dims(a,axis=0)

array([[22, 53, 92, 41, 97,  1, 29, 98,  6, 29, 61, 20, 22, 67, 31]])

In [28]:
# 1D to 2D
np.expand_dims(a,axis=0).shape

(1, 15)

In [32]:
# 1D to 2D
print(np.expand_dims(a,axis=1))
print("\n shape of a is",np.expand_dims(a,axis=1).shape)

[[22]
 [53]
 [92]
 [41]
 [97]
 [ 1]
 [29]
 [98]
 [ 6]
 [29]
 [61]
 [20]
 [22]
 [67]
 [31]]

 shape of a is (15, 1)


# np.where

In [33]:
a

array([22, 53, 92, 41, 97,  1, 29, 98,  6, 29, 61, 20, 22, 67, 31])

In [34]:
# find index position value more 50
np.where(a>50)

(array([ 1,  2,  4,  7, 10, 13], dtype=int64),)

In [35]:
# replace all value with zero
# np.where(condition,true,false)
np.where(a>50,0,a)

array([22,  0,  0, 41,  0,  1, 29,  0,  6, 29,  0, 20, 22,  0, 31])

In [36]:
# even no replace with zero
np.where(a%2==0,0,a)

array([ 0, 53,  0, 41, 97,  1, 29,  0,  0, 29, 61,  0,  0, 67, 31])

# np.argmax()
- retrun ondexies of maximun elements of array in particular axis

In [3]:
a

array([47, 89, 27, 53, 97, 86, 98, 97, 58, 90,  4, 55, 16, 51, 25])

In [2]:
np.argmax(a)

6

In [5]:
b

array([[30, 44, 60,  1],
       [66, 47, 26, 90],
       [61, 12, 68, 30],
       [46, 47, 41, 83],
       [80, 63, 19, 55],
       [32, 80, 38, 60]])

In [6]:
np.argmax(b,axis=0)

array([4, 5, 2, 1], dtype=int64)

In [7]:
np.argmax(b,axis=1)

array([2, 3, 2, 3, 0, 1], dtype=int64)

# np.argmin()

In [8]:
np.argmin(b,axis=0)

array([0, 2, 4, 0], dtype=int64)

In [9]:
np.argmin(b,axis=1)

array([3, 2, 1, 2, 2, 0], dtype=int64)

# np.cumsum
- return cumlative-sum of the arrays

In [17]:
np.cumsum(b)

array([  30,   74,  134,  135,  201,  248,  274,  364,  425,  437,  505,
        535,  581,  628,  669,  752,  832,  895,  914,  969, 1001, 1081,
       1119, 1179])

In [14]:
np.cumsum(b,axis=1)

array([[ 30,  74, 134, 135],
       [ 66, 113, 139, 229],
       [ 61,  73, 141, 171],
       [ 46,  93, 134, 217],
       [ 80, 143, 162, 217],
       [ 32, 112, 150, 210]])

In [20]:
# np.cumprod
np.cumprod(b,axis=0)

array([[         30,          44,          60,           1],
       [       1980,        2068,        1560,          90],
       [     120780,       24816,      106080,        2700],
       [    5555880,     1166352,     4349280,      224100],
       [  444470400,    73480176,    82636320,    12325500],
       [ 1338150912,  1583446784, -1154787136,   739530000]])

# np.percitile

In [26]:
np.percentile(b,75,axis=0)

array([64.75, 59.  , 55.25, 77.25])

In [27]:
np.percentile(b,95,axis=0)

array([76.5 , 75.75, 66.  , 88.25])

In [28]:
np.percentile(b,50), np.median(b)

(47.0, 47.0)

# np.histogram
- present the frequency of data distribution in the graphical-form

In [30]:
np.histogram(a) # frequency count

(array([1, 1, 2, 0, 1, 4, 0, 0, 1, 5], dtype=int64),
 array([ 4. , 13.4, 22.8, 32.2, 41.6, 51. , 60.4, 69.8, 79.2, 88.6, 98. ]))

In [31]:
np.histogram(a,bins=range(0,100,10))

(array([1, 1, 2, 0, 1, 4, 0, 0, 3], dtype=int64),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

# np.corrcoef
- Return pearson product-moment correlation coefficient

In [38]:
np.corrcoef(b)

array([[ 1.        , -0.99143781,  0.35237924, -0.91715265, -0.495449  ,
        -0.16237721],
       [-0.99143781,  1.        , -0.33981   ,  0.85793192,  0.59994838,
         0.1323747 ],
       [ 0.35237924, -0.33981   ,  1.        , -0.41156206, -0.34418086,
        -0.97087334],
       [-0.91715265,  0.85793192, -0.41156206,  1.        ,  0.14259164,
         0.29658027],
       [-0.495449  ,  0.59994838, -0.34418086,  0.14259164,  1.        ,
         0.13567991],
       [-0.16237721,  0.1323747 , -0.97087334,  0.29658027,  0.13567991,
         1.        ]])

In [39]:
sal = np.array([1000,2000,3000,4000])
exp = np.array([1,2,3,4])


np.corrcoef(sal,exp)

array([[1., 1.],
       [1., 1.]])

In [41]:
sal = np.array([1000,2000,3000,4000])
exp = np.array([1,2,3,4])
age =np.array([4,3,2,1])

np.corrcoef(sal,age)

array([[ 1., -1.],
       [-1.,  1.]])

# np.isin

In [43]:
a

array([47, 89, 27, 53, 97, 86, 98, 97, 58, 90,  4, 55, 16, 51, 25])

In [42]:
np.isin(a,5)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [45]:
np.isin(a,[55,16,51])

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True, False])

In [46]:
a[np.isin(a,[55,16,51])]

array([55, 16, 51])

# np.flip

In [47]:
np.flip(a)

array([25, 51, 16, 55,  4, 90, 58, 97, 98, 86, 97, 53, 27, 89, 47])

In [48]:
np.flip(b)

array([[60, 38, 80, 32],
       [55, 19, 63, 80],
       [83, 41, 47, 46],
       [30, 68, 12, 61],
       [90, 26, 47, 66],
       [ 1, 60, 44, 30]])

In [49]:
np.flip(b,axis=0)

array([[32, 80, 38, 60],
       [80, 63, 19, 55],
       [46, 47, 41, 83],
       [61, 12, 68, 30],
       [66, 47, 26, 90],
       [30, 44, 60,  1]])

In [50]:
np.flip(b,axis=1)

array([[ 1, 60, 44, 30],
       [90, 26, 47, 66],
       [30, 68, 12, 61],
       [83, 41, 47, 46],
       [55, 19, 63, 80],
       [60, 38, 80, 32]])

# np.put
- replaces specific element in array

In [51]:
a

array([47, 89, 27, 53, 97, 86, 98, 97, 58, 90,  4, 55, 16, 51, 25])

In [52]:
np.put(a,[10,12],[5,17])

In [53]:
a

array([47, 89, 27, 53, 97, 86, 98, 97, 58, 90,  5, 55, 17, 51, 25])

# np.delete

In [55]:
np.delete(a,[10,12])

array([47, 89, 27, 53, 97, 86, 98, 97, 58, 90, 55, 51, 25])

# set function
- np.union1d
- np.intersection1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [56]:
m = np.array([1,2,3,4,5,6])
n = np.array([3,4,5,6,7,8,])

print(m)
print(n)

[1 2 3 4 5 6]
[3 4 5 6 7 8]


In [57]:
np.union1d(n,m)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
np.intersect1d(n,m)

array([3, 4, 5, 6])

In [59]:
np.setdiff1d(n,m)

array([7, 8])

In [60]:
np.setdiff1d(m,n)

array([1, 2])

In [62]:
np.setxor1d(n,m) #uncommon

array([1, 2, 7, 8])

In [64]:
np.in1d(n,[2,3,5])

array([ True, False,  True, False, False, False])

In [66]:
n[np.in1d(n,[2,3,5])]

array([3, 5])

# np.clip

In [68]:
a

array([47, 89, 27, 53, 97, 86, 98, 97, 58, 90,  5, 55, 17, 51, 25])

In [70]:
np.clip(a,a_min=25,a_max=50) #clip lowe value=25, clip upper value=50

array([47, 50, 27, 50, 50, 50, 50, 50, 50, 50, 25, 50, 25, 50, 25])

In [ ]:
# 17. np.swapaxes

In [71]:
b

array([[30, 44, 60,  1],
       [66, 47, 26, 90],
       [61, 12, 68, 30],
       [46, 47, 41, 83],
       [80, 63, 19, 55],
       [32, 80, 38, 60]])

In [76]:
np.swapaxes(b,axis1=2,axis2=3)

AxisError: axis1: axis 2 is out of bounds for array of dimension 2

# 18. np.uniform
np.uniform(a)

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals